### ISSUE TITLE
To delete

### ISSUE THREAD

**Issue by jcheron** [dixplo/Datamaps-3TM#32]
J'ai oublié de supprimer cette ligne:
https://github.com/dixplo/Datamaps-3TM/blob/bb2ffaad1c4a12bdb464faa9dd347456901c2cf8/src/main/java/fr/tm/datasmap/controller/MapController.java#L39

**Comment by ThomasFont3721** [comment]
Mais alors on initialise jamais map ?

**Comment by jcheron** [comment]
> Mais alors on initialise jamais map ?
Si dans la méthode `initmap` de **Vue**, appelée sur l'event `mounted`
Essayez, vous allez bien voir

**Comment by ThomasFont3721** [comment]
Ah oui en effet merci beaucoup
